
export const ROLES = {
  ADMIN: "ADMIN",
  AGENT: "AGENT",
  CUSTOMER: "CUSTOMER",
};

export const OTP_CHANNELS = ["EMAIL", "PHONE"];

export const PRODUCT_TYPES = ["HEALTH", "MOTOR", "LIFE", "TRAVEL"];

export const PREMIUM_TYPES = ["ONE_TIME", "ANNUAL"];

export const PAYMENT_MODES = ["UPI", "CARD", "NET_BANKING", "CASH"];

export const PAYMENT_STATUSES = ["SUCCESS", "FAILED", "PENDING"];

export const POLICY_STATUSES = ["PENDING_PAYMENT", "ACTIVE", "EXPIRED", "CANCELLED"];

export const CLAIM_STATUSES = [
  "SUBMITTED",
  "UNDER_REVIEW",
  "RECOMMENDED_FOR_APPROVAL",
  "RECOMMENDED_FOR_REJECTION",
  "APPROVED",
  "REJECTED",
];

export const AGENT_REVIEW_OPTIONS = ["RECOMMENDED_FOR_APPROVAL", "RECOMMENDED_FOR_REJECTION"];

export const ADMIN_DECISION_OPTIONS = ["APPROVED", "REJECTED"];

export const DOCUMENT_TYPES = ["MEDICAL_REPORT", "POLICE_REPORT", "INVOICE", "PHOTO", "OTHER"];
